various fixes

diff --git a/mat b/mat
--- a/mat
+++ b/mat
@@ -7,28 +7,30 @@ for func in /usr/lib/mat/*; do
     fi
 done
 
-PREFIX=""
+export PREFIX=""
 CONTAINER_URL="localhost/mat"
 
-if [[ "$@" == *"--init"* ]]; then PREFIX="${@: -1}"; fi
+if [[ "$@" == *"--init"* ]]; then export PREFIX="${@: -1}"; fi
 
-if systemd-inhibit --who="mat" --what="idle" sleep 0.1 &>/dev/null && \
-    ! { systemd-inhibit --list | grep -q "mat-rootful-ops" ; } && [[ "$(id -u)" == "0" ]]; then
-    set -e
-    systemd-inhibit --what="idle:sleep:shutdown" --who="mat-rootful-ops" --why="Doing important stuff" \
-        mat "$@"
-    exit 0
+if systemd-inhibit --who="mat" --what="idle" sleep 0.1 &>/dev/null && [[ "$(id -u)" == "0" ]]; then
+    if { systemd-inhibit --list | grep -q mat-rootful-ops ; }; then
+        :
+    else
+        systemd-inhibit --what="idle:sleep:shutdown" --who="mat-rootful-ops" \
+            --why="Doing important stuff" -- mat "$@"
+        exit 0
+    fi
 fi
 
 if [[ "$(id -u)" == "0" ]]; then
-    [[ ! -f "$PREFIX/etc/.mat.lock" ]] && \
+    [[ ! -f "$PREFIX/etc/mat/.mat.lock" ]] && \
         mkdir -p "$PREFIX/etc/mat" && touch "$PREFIX/etc/mat/.mat.lock"
 
-    exec {MAT_LOCK}<>"$PREFIX/etc/.mat.lock" || \
+    exec {MAT_LOCK}<>"$PREFIX/etc/mat/.mat.lock" || \
         { printf "Couldn't set lock fd.\n" && exit 1 ; }
 
     printf "Acquiring lock...\n"
-    flock -x "$MAT_LOCK"
+    flock -x "$MAT_LOCK" || { printf "Couldn't acquire lock!\n" ; }
 fi
 
 case "$1" in
@@ -76,4 +78,3 @@ case "$1" in
         echo default
         ;;
 esac
-
