add verify function

diff --git a/lib/containerer b/lib/containerer
--- a/lib/containerer
+++ b/lib/containerer
@@ -16,11 +16,15 @@ pull_image() {
 }
 
 update_store() {
-    if [[ -f /.mat/.current && "$(cat /.mat/.current)" != "" ]]; then
-        failed="$(cat /.mat/.current)"
-        printf "Cleaning up $failed...\n"
-        rm -rf "/.mat/.store/${failed:?}"
-        echo "" > ./.current
+    if [[ -f .current && "$(cat .current)" != "" ]]; then
+        printf "Cleaning up failed packages...\n"
+        cat .current | xargs -I{} -P"$(("$(nproc --all)"/2))" \
+            rm -rf .store/{}
+        echo "" > .current
+    fi
+
+    if [[ ! -d .store ]]; then
+        mkdir .store
     fi
 
     SOURCE_IMAGE="$1"
@@ -29,17 +33,24 @@ update_store() {
     podman create --name mat-tmp "$SOURCE_IMAGE"
     CMOUNT="$(podman mount mat-tmp)"
 
-    cp -fa "$CMOUNT/.mat/.pkgs" "/.mat/.pkgs$deployment"
-    read -ra pkg_list <<< "$(cat /.mat/.pkgs"$deployment" | tr "\n" " ")"
+    cp -fa "$CMOUNT/.mat/pkgs" "pkgs$deployment"
 
-    for package in "${pkg_list[@]}"; do
-        if [[ ! -d "/.mat/.store/$package" ]]; then
+    install_package() {
+        package="$1"
+        if [[ ! -d ".store/$package" ]]; then
             printf "Storing package $package...\n"
-            echo "$package" > /.mat/.current
-            rsync -aHlx "$CMOUNT/.mat/.store/$package" /.mat/.store/ 2>/dev/null || :
-            echo "" > /.mat/.current
+            rsync -aHlx "$CMOUNT/.mat/.store/$package" .store/ || :
         fi
-    done
+    }
+
+    export -f install_package
+    export CMOUNT
+
+    cat "pkgs$deployment" | xargs -n1 -P"$(("$(nproc --all)"**2))" \
+        bash -c 'install_package "$@"' _
+
+    unset -f install_package
+    unset CMOUNT
 
     podman unmount mat-tmp
     podman rm mat-tmp
